package sbnz.integracija;

import app.enums.KrvniPritisakStatus;
import app.enums.BMIStatus;

import java.time.Duration;

global java.util.Deque controlSet;
global java.util.Deque usersNotified;

import app.dto.HeartBeatDTO;

declare AlreadyProcessed
end

rule "HeartBeat rule"
	when
		$h : HeartBeatDTO ($time : startTime)
		not(HeartBeatDTO( this != $h, this after[0s, 5s] $h))
	then
		$h.setText("Heartbeat not recieved in 5s!");
		controlSet.push($h);
end


rule "HeartBeat status DisiteDuboko"
	salience 4
	when
		$h : HeartBeatDTO (heartRatePerMinute > upperLimit * 1.05 && (krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_1 ||
											  						krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_2) &&
						Duration.between(startTime, timeNow).toMinutes() > 10)
	then
		$h.setText("Disite Duboko");
end

rule "Napravite Pauzu od 2min, hodajte"
	salience 3
	when
		$h : HeartBeatDTO (heartRatePerMinute > upperLimit * 1.1 && (krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_1 ||
											  						krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_2) &&
							Duration.between(startTime, timeNow).toMinutes() > 5)							
	then
		$h.setText("Napravite Pauzu od 2min, hodajte");
end

rule "HeartBeat status Napravite Pauzu od 5min, hodajte "
	salience 2
	when
		$h : HeartBeatDTO (heartRatePerMinute > upperLimit * 1.2 && (krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_1 ||
											  						krvniPritisak == KrvniPritisakStatus.HIPERTENZIJA_2 ||
											  						bmiStatus == BMIStatus.GOJAZNOST ||
											  						bmiStatus == BMIStatus.EKSTREMNA_GOJAZNOST) &&
							Duration.between(startTime, timeNow).toMinutes() > 1)									  
	then
		$h.setText("Napravite Pauzu od 5min, hodajte ");
end

rule "HeartBeat status Prestanite sa vezbanjem"
	salience 1
	when
		$h : HeartBeatDTO (heartRatePerMinute > upperLimit * 1.3)									  
	then
		$h.setText("Prestanite sa vezbanjem");
end


rule "HeartBeat status Ubrzajte tempo"
	when
			$h : HeartBeatDTO (heartRatePerMinute < lowerLimit && (krvniPritisak != KrvniPritisakStatus.HIPERTENZIJA_1 ||
											  				   krvniPritisak != KrvniPritisakStatus.HIPERTENZIJA_2) &&
							Duration.between(startTime, timeNow).toMinutes() > 1)									  
	then
		$h.setText("Ubrzajte tempo");
end