package sbnz.integracija;

import app.dto.QuerySportDTO;
import app.model.IndividualniSport;
import app.model.IndividualnaKategorija;
import app.enums.IndividualnaPodkategorija;

import app.enums.CenaSporta;

import java.util.List

rule "Caluculate scores for INDIVIDUALNI sports"
no-loop
    when                            
        $query: QuerySportDTO(
	        $sports : odabrani_tip,
	         
	        $preciznost : preciznost, 
	        $izdrzljivost : izdrzljivost,
	        $tehnika : tehnika,
	        $brzina : brzina,
	        $snaga : snaga,
	        
	        tipSporta == TipSporta.INDIVIDUALNI && indPodkategorija == null && cena == null && odabrani_tip != null);
	        
	    Number($max: doubleValue) from accumulate(
	    	IndividualniSport($current : this) from $sports,
	    	max($current.calculateMatchScore($query.preciznost,$query.izdrzljivost,$query.tehnika,$query.brzina,$query.snaga))
	    );
	    
	    $sport : IndividualniSport(this.calculateMatchScore($query.preciznost,$query.izdrzljivost,$query.tehnika,$query.brzina,$query.snaga) == $max) from $sports;
	         
    then
    	$query.setOdabraniSport($sport);
        update($query);
end

