package sbnz.integracija;

import app.dto.QuerySportDTO;
import app.model.TimskiSport;
import app.model.TimskaKategorija;
import app.enums.TimskaPodkategorija;

import app.enums.CenaSporta;

import java.util.List

rule "Filter PODKATEGORIJE for TIMSKI sports "
    when                            
        $query: QuerySportDTO($podkat: timPodkategorija, $sports : odabrani_tip, tipSporta == TipSporta.TIMSKI  && odabrani_tip != null && timPodkategorija != null && cena == null);  

        $sportovi : List() from accumulate(
        	TimskiSport($sport : this, kategorije.size() > 0) from $sports,
        	init(List<TimskiSport> results = new ArrayList<TimskiSport>(); ),
        	action(
        			for( TimskaKategorija kat : $sport.getKategorije()){
        				if(kat.getPodkategorija() == $podkat){
        					results.add($sport);
        				}
        			}
        		),
        	result(results)
        )
        	
    then    	
    	$query.setOdabrani_tip($sportovi);
    	$query.setTimPodkategorija(null);
        update($query);
end

